#!/bin/bash
# $1 : current directory
# $2 : current file
#
# rename current directory to current file,
# after removing the extension
#
# Example:
# /media/Movies/asdsfsf renames to
# /media/Movies/The Game(1993)
#
# if executed on a file called
#   The Game (1993).mkv
# inside /media/Movies/asdsfsf

P=$(dirname "$1")
F=$(echo "$2" | sed 's/\.[^\.]*$//')
mv "$1" "$P"/"$F"
